CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: parseC.cpp
		g++  $(CXXFLAGS)  parseC.cpp   -o   parseC.out
clean:
		echo ----------------removing executable program main--------------------
		/bin/rm parseC.out