CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: lab2.cpp
				g++  $(CXXFLAGS)  lab2.cpp   -o   lab2
clean:
				echo ----------------removing executable program main--------------------
				/bin/rm lab2
