CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: MusicLibrary.cpp
		g++  $(CXXFLAGS)  MusicLibrary.cpp   -o   MusicLibrary
clean:
		echo ----------------removing executable program main--------------------
		/bin/rm MusicLibrary