CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: musicPlayer.cpp
		g++  $(CXXFLAGS)  musicPlayer.cpp   -o   musicPlayer
clean:
		echo ----------------removing executable program main--------------------
		/bin/rm musicPlayer