// // normal_distribution example
// #include <iostream>
// #include <chrono>
// #include <random>

// using namespace std;

// int getUniformRandomDistribution(int no_processors,int no_memory_modules) {
//     random_device rd;  //Will be used to obtain a seed for the random number engine
//     mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
//     uniform_int_distribution<> distrib(1, no_memory_modules);
//     return distrib(gen);
// }

// int getNormalRandomDistribution(int no_memory_modules,double mean,double standard_deviation) {
//     // construct a trivial random generator engine from a time-based seed:
//     unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
//     std::default_random_engine generator (seed);

//     std::normal_distribution<double> distribution (mean, standard_deviation);
//     return distribution(generator);
// }

// int main()
// {

//     // std::random_device rd;  //Will be used to obtain a seed for the random number engine
//     // std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
//     // std::uniform_int_distribution<> distrib(1, 6);

//     // for (int n=0; n<10; ++n)
//     //     //Use `distrib` to transform the random unsigned int generated by gen into an int in [1, 6]
//     //     std::cout << distrib(gen) << ' ';
//     // std::cout << '\n';

//     // // construct a trivial random generator engine from a time-based seed:
//     // unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
//     // std::default_random_engine generator (seed);

//     // std::normal_distribution<double> distribution (0.0,1.0);

//     // std::cout << "some Normal-distributed(0.0,1.0) results:" << std::endl;
//     // for (int i=0; i<10; ++i)
//     // std::cout << distribution(generator) << std::endl;

//     // return 0;

//     cout << getUniformRandomDistribution(10, 7) << endl;
//     cout << getNormalRandomDistribution(10, 2, 2) << endl;
// }