CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: hw7.cpp
		g++  $(CXXFLAGS)  hw7.cpp   -o   hw7
clean:
		echo ----------------removing executable program main--------------------
		/bin/rm hw7