CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: lab3.cpp
				g++  $(CXXFLAGS)  lab3.cpp   -o   lab3.out
clean:
				echo ----------------removing executable program main--------------------
				/bin/rm lab3.out
