CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: hw6.cpp
		g++  $(CXXFLAGS)  hw6.cpp   -o   hw6
clean:
		echo ----------------removing executable program main--------------------
		/bin/rm hw6