all: strstr numOccurrences anagram strstrx


strstr: strstr.cpp
		g++  $(CXXFLAGS)  strstr.cpp   -o   strstr

numOccurrences: numOccurrences.cpp
		g++  $(CXXFLAGS)  numOccurrences.cpp   -o   numOccurrences


anagram: anagram.cpp
		g++  $(CXXFLAGS)  anagram.cpp   -o   anagram

strstrx: strstrx.cpp
		g++  $(CXXFLAGS)  strstrx.cpp   -o   strstrx

clean:
		echo ----------------removing executable program strstr numOccurrences anagram strstrx--------------------
		/bin/rm strstr numOccurrences anagram strstrx