CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: hw5.cpp
		g++  $(CXXFLAGS)  hw5.cpp   -o   hw5
clean:
		echo ----------------removing executable program main--------------------
		/bin/rm hw5