CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
main: lab1.cpp
                g++  $(CXXFLAGS)  lab1.cpp   -o   lab1
clean:
                echo ----------------removing executable program main--------------------
                /bin/rm lab1